name: onepose
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8 # need to keep this at 3.8 since pydegensac does not work on 3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.6
  - ipython
  - tqdm
  - matplotlib
  - pylint
  - conda-forge::jupyterlab
  - conda-forge::h5py=3.1.0
  - conda-forge::loguru=0.5.3
  - conda-forge::scipy
  - conda-forge::numba
  - conda-forge::ipdb
  - conda-forge::colmap
  - pip
  - pip:
    - -r requirements.txt